[package]
name = "core-native"
version = "0.1.0"
authors = ["Maximilian Alexander <max@ditto.live>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
node-bindgen = { version = "3.0.0" }

[build-dependencies]
node-bindgen = { version = "3.0.0", features = ["build"] }