[package]
name = "core-web"
version = "0.1.0"
authors = ["Maximilian Alexander <max@ditto.live>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
async-trait = "0.1"
js-sys = "0.3"
